/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.quarkus.maven;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.apache.maven.execution.MavenSession;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.Component;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;
import org.apache.maven.project.ProjectBuilder;

/**
 * Detects changed modules based on git diff and analyzes transitive dependencies
 * to determine which modules need to be built and tested in CI.
 *
 * @since 3.32.0
 */
@Mojo(name = "detect-changed-modules", threadSafe = true, aggregator = true)
public class DetectChangedModulesMojo extends AbstractMojo {

    /**
     * The output file where the JSON result will be written.
     */
    @Parameter(property = "cq.outputFile", defaultValue = "${project.build.directory}/changed-modules.json")
    private File outputFile;

    /**
     * Path to the test categories YAML file.
     */
    @Parameter(property = "cq.testCategoriesFile", defaultValue = "tooling/scripts/test-categories.yaml")
    private File testCategoriesFile;

    /**
     * Force a full build regardless of changes detected.
     */
    @Parameter(property = "cq.forceFullBuild", defaultValue = "${env.FORCE_FULL_BUILD}")
    private String forceFullBuild;

    @Parameter(defaultValue = "${session}", readonly = true, required = true)
    private MavenSession session;

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    @Component
    private ProjectBuilder projectBuilder;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        try {
            // Check if full build is forced
            if ("true".equalsIgnoreCase(forceFullBuild)) {
                getLog().info("Full build forced via FORCE_FULL_BUILD environment variable");
                writeFullBuildResult();
                return;
            }

            // Read Scalpel report (generated by Scalpel Maven extension)
            ScalpelReport report = readScalpelReport();

            // Check if Scalpel triggered a full build
            if (report.isFullBuildTriggered()) {
                getLog().info("Scalpel triggered full build due to: " + report.getTriggerFile());
                writeFullBuildResult();
                return;
            }

            // Extract affected modules from Scalpel report
            Set<String> affectedModules = new LinkedHashSet<>();
            if (report.getAffectedModules() != null) {
                for (ScalpelReport.ScalpelModule module : report.getAffectedModules()) {
                    String path = module.getPath();
                    // Scalpel uses empty string for root module, skip it
                    if (path != null && !path.isEmpty()) {
                        affectedModules.add(path);
                    }
                }
            }

            getLog().info("Scalpel detected " + affectedModules.size() + " affected modules");

            if (affectedModules.isEmpty()) {
                getLog().info("No modules affected - generating empty build matrix");
                writeEmptyBuildResult();
                return;
            }

            getLog().info("Affected modules: " + affectedModules);

            // Generate output (Scalpel already handles transitive dependencies)
            generateOutput(affectedModules, false);

        } catch (Exception e) {
            getLog().error("Error detecting changed modules, falling back to full build", e);
            try {
                writeFullBuildResult();
            } catch (IOException ioException) {
                throw new MojoExecutionException("Failed to write fallback result", ioException);
            }
        }
    }

    private ScalpelReport readScalpelReport() throws IOException {
        // Scalpel writes report to target/scalpel-report.json by default
        Path reportPath = project.getBasedir().toPath().resolve("target/scalpel-report.json");

        if (!Files.exists(reportPath)) {
            throw new IOException("Scalpel report not found at: " + reportPath
                    + ". Please ensure Scalpel Maven extension is configured in .mvn/extensions.xml"
                    + " and that 'mvn validate' has been run to generate the report.");
        }

        ObjectMapper mapper = new ObjectMapper();
        ScalpelReport report = mapper.readValue(reportPath.toFile(), ScalpelReport.class);

        getLog().info("Read Scalpel report (version " + report.getScalpelVersion() + ")");
        getLog().info("Base branch: " + report.getBaseBranch());
        getLog().info("Changed files: " + (report.getChangedFiles() != null ? report.getChangedFiles().size() : 0));

        return report;
    }

    private Set<String> getAllModulesInDirectory(String directoryPrefix) {
        Set<String> modules = new LinkedHashSet<>();

        // Remove trailing slash if present
        String dirPath = directoryPrefix.endsWith("/") ? directoryPrefix.substring(0, directoryPrefix.length() - 1)
                : directoryPrefix;
        Path directory = project.getBasedir().toPath().resolve(dirPath);

        if (Files.exists(directory) && Files.isDirectory(directory)) {
            try {
                Files.list(directory)
                        .filter(Files::isDirectory)
                        .filter(path -> !path.getFileName().toString().startsWith("."))
                        .filter(path -> !path.getFileName().toString().equals("target"))
                        .filter(path -> Files.exists(path.resolve("pom.xml")))
                        .map(path -> path.getFileName().toString())
                        .forEach(modules::add);
            } catch (IOException e) {
                getLog().warn("Could not list modules in directory: " + directory, e);
            }
        } else {
            getLog().warn("Directory does not exist: " + directory);
        }

        return modules;
    }

    private void generateOutput(Set<String> affectedModules) throws IOException {
        generateOutput(affectedModules, false);
    }

    private void generateOutput(Set<String> affectedModules, boolean isFullBuild) throws IOException {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("full-build", isFullBuild);
        result.put("changed-modules", new ArrayList<>(affectedModules));

        // Categorize modules
        Map<String, Set<String>> categorizedModules = categorizeModules(affectedModules);
        result.put("native-tests", generateNativeTestsMatrix(categorizedModules.get("integration-tests"), isFullBuild));
        result.put("functional-extension-tests", generateFunctionalTestsConfig(categorizedModules, isFullBuild));
        result.put("extensions-jvm-tests",
                generateJvmTestsConfig(categorizedModules.get("integration-tests-jvm"), isFullBuild));
        result.put("integration-tests-alternative-jdk",
                generateAlternativeJdkConfig(categorizedModules.get("integration-tests"), isFullBuild));

        writeJsonResult(result);
    }

    private Map<String, Set<String>> categorizeModules(Set<String> modules) {
        Map<String, Set<String>> categorized = new HashMap<>();
        categorized.put("extensions", new LinkedHashSet<>());
        categorized.put("extensions-core", new LinkedHashSet<>());
        categorized.put("extensions-jvm", new LinkedHashSet<>());
        categorized.put("integration-tests", new LinkedHashSet<>());
        categorized.put("integration-tests-jvm", new LinkedHashSet<>());
        categorized.put("test-framework", new LinkedHashSet<>());
        categorized.put("tooling", new LinkedHashSet<>());
        categorized.put("catalog", new LinkedHashSet<>());
        categorized.put("other", new LinkedHashSet<>());

        for (String module : modules) {
            if (module.startsWith("extensions-core/")) {
                categorized.get("extensions-core").add(module.substring("extensions-core/".length()));
            } else if (module.startsWith("extensions-jvm/")) {
                categorized.get("extensions-jvm").add(module.substring("extensions-jvm/".length()));
            } else if (module.startsWith("extensions/")) {
                categorized.get("extensions").add(module.substring("extensions/".length()));
            } else if (module.startsWith("integration-tests-jvm/")) {
                categorized.get("integration-tests-jvm").add(module.substring("integration-tests-jvm/".length()));
            } else if (module.startsWith("integration-tests/")) {
                categorized.get("integration-tests").add(module.substring("integration-tests/".length()));
            } else if (module.startsWith("test-framework/")) {
                categorized.get("test-framework").add(module.substring("test-framework/".length()));
            } else if (module.startsWith("tooling/")) {
                categorized.get("tooling").add(module.substring("tooling/".length()));
            } else if (module.startsWith("catalog/")) {
                categorized.get("catalog").add(module.substring("catalog/".length()));
            } else {
                categorized.get("other").add(module);
            }
        }

        return categorized;
    }

    private Map<String, Object> generateNativeTestsMatrix(Set<String> integrationTestModules, boolean isFullBuild)
            throws IOException {
        Map<String, Object> matrix = new LinkedHashMap<>();

        if (isFullBuild) {
            // Full build - use test-categories.yaml for balanced groups
            Map<String, List<String>> categories = loadTestCategories();
            List<Map<String, Object>> include = new ArrayList<>();
            for (Map.Entry<String, List<String>> entry : categories.entrySet()) {
                Map<String, Object> item = new LinkedHashMap<>();
                item.put("category", entry.getKey());
                item.put("modules", new ArrayList<>(entry.getValue()));
                include.add(item);
            }
            matrix.put("include", include);
            return matrix;
        }

        // Incremental build
        if (integrationTestModules.isEmpty()) {
            matrix.put("include", Collections.emptyList());
            return matrix;
        }

        // Incremental build - dynamically distribute modules across groups for maximum parallelism
        // Ignore test-categories.yaml and spread modules evenly across up to 13 groups
        final int MAX_GROUPS = 13;
        List<String> moduleList = new ArrayList<>(integrationTestModules);
        int numGroups = Math.min(moduleList.size(), MAX_GROUPS);

        List<Map<String, Object>> include = new ArrayList<>();
        for (int i = 0; i < numGroups; i++) {
            List<String> groupModules = new ArrayList<>();
            // Distribute modules round-robin across groups
            for (int j = i; j < moduleList.size(); j += numGroups) {
                groupModules.add(moduleList.get(j));
            }

            if (!groupModules.isEmpty()) {
                Map<String, Object> item = new LinkedHashMap<>();
                item.put("category", String.format("group-%02d", i + 1));
                item.put("modules", groupModules);
                include.add(item);
            }
        }

        matrix.put("include", include);
        return matrix;
    }

    private Map<String, Object> generateFunctionalTestsConfig(Map<String, Set<String>> categorizedModules,
            boolean isFullBuild) {
        Map<String, Object> config = new LinkedHashMap<>();
        Map<String, Set<String>> modulesByDirectory = new LinkedHashMap<>();

        if (isFullBuild) {
            // Full build - include ALL modules from each directory
            modulesByDirectory.put("extensions-core", getAllModulesInDirectory("extensions-core"));
            modulesByDirectory.put("extensions", getAllModulesInDirectory("extensions"));
            modulesByDirectory.put("test-framework", getAllModulesInDirectory("test-framework"));
            modulesByDirectory.put("tooling", getAllModulesInDirectory("tooling"));
            modulesByDirectory.put("catalog", getAllModulesInDirectory("catalog"));
        } else {
            // Incremental build - only include affected modules
            if (!categorizedModules.get("extensions-core").isEmpty()) {
                modulesByDirectory.put("extensions-core", categorizedModules.get("extensions-core"));
            }
            if (!categorizedModules.get("extensions").isEmpty()) {
                modulesByDirectory.put("extensions", categorizedModules.get("extensions"));
            }
            if (!categorizedModules.get("test-framework").isEmpty()) {
                modulesByDirectory.put("test-framework", categorizedModules.get("test-framework"));
            }
            if (!categorizedModules.get("tooling").isEmpty()) {
                modulesByDirectory.put("tooling", categorizedModules.get("tooling"));
            }
            if (!categorizedModules.get("catalog").isEmpty()) {
                modulesByDirectory.put("catalog", categorizedModules.get("catalog"));
            }
        }

        // Create one entry per directory with its specific modules
        List<Map<String, Object>> include = new ArrayList<>();
        for (Map.Entry<String, Set<String>> entry : modulesByDirectory.entrySet()) {
            if (!entry.getValue().isEmpty()) {
                Map<String, Object> item = new LinkedHashMap<>();
                item.put("directory", entry.getKey());
                item.put("modules", new ArrayList<>(entry.getValue()));
                include.add(item);
            }
        }

        config.put("include", include);
        return config;
    }

    private Map<String, Object> generateJvmTestsConfig(Set<String> jvmTestModules, boolean isFullBuild) {
        Map<String, Object> config = new LinkedHashMap<>();
        List<Map<String, Object>> include = new ArrayList<>();

        Set<String> modulesToTest = jvmTestModules;
        if (isFullBuild) {
            // Full build - get ALL modules from integration-tests-jvm
            modulesToTest = getAllModulesInDirectory("integration-tests-jvm/");
        }

        if (!modulesToTest.isEmpty()) {
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("category", "");
            item.put("modules", new ArrayList<>(modulesToTest));
            include.add(item);
        }

        config.put("include", include);
        return config;
    }

    private Map<String, Object> generateAlternativeJdkConfig(Set<String> integrationTestModules, boolean isFullBuild) {
        Map<String, Object> config = new LinkedHashMap<>();
        List<Map<String, Object>> include = new ArrayList<>();

        Set<String> modulesToTest = integrationTestModules;
        if (isFullBuild) {
            // Full build - get ALL modules from integration-tests
            modulesToTest = getAllModulesInDirectory("integration-tests/");
        }

        if (modulesToTest.isEmpty()) {
            config.put("include", include);
            return config;
        }

        // Split modules into two groups for parallel execution
        List<String> moduleList = new ArrayList<>(modulesToTest);
        int midpoint = moduleList.size() / 2;

        List<String> group1Modules = moduleList.subList(0, midpoint);
        List<String> group2Modules = moduleList.subList(midpoint, moduleList.size());

        if (!group1Modules.isEmpty()) {
            Map<String, Object> group1 = new LinkedHashMap<>();
            group1.put("category", "group-01");
            group1.put("modules", new ArrayList<>(group1Modules));
            include.add(group1);
        }

        if (!group2Modules.isEmpty()) {
            Map<String, Object> group2 = new LinkedHashMap<>();
            group2.put("category", "group-02");
            group2.put("modules", new ArrayList<>(group2Modules));
            include.add(group2);
        }

        config.put("include", include);
        return config;
    }

    private Map<String, List<String>> loadTestCategories() throws IOException {
        Map<String, List<String>> categories = new LinkedHashMap<>();

        if (!testCategoriesFile.exists()) {
            getLog().warn("Test categories file not found: " + testCategoriesFile);
            return categories;
        }

        // Simple YAML parser for the test-categories.yaml structure
        List<String> lines = Files.readAllLines(testCategoriesFile.toPath(), StandardCharsets.UTF_8);
        String currentCategory = null;

        for (String line : lines) {
            line = line.trim();
            if (line.isEmpty() || line.startsWith("#")) {
                continue;
            }

            if (line.endsWith(":")) {
                // Category line
                currentCategory = line.substring(0, line.length() - 1);
                categories.put(currentCategory, new ArrayList<>());
            } else if (line.startsWith("-") && currentCategory != null) {
                // Module line
                String module = line.substring(1).trim();
                categories.get(currentCategory).add(module);
            }
        }

        return categories;
    }

    private void writeFullBuildResult() throws IOException {
        // For full build, generate output with ALL modules
        generateOutput(Collections.emptySet(), true);
    }

    private void writeEmptyBuildResult() throws IOException {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("full-build", false);
        result.put("changed-modules", Collections.emptyList());
        result.put("native-tests", Collections.singletonMap("include", Collections.emptyList()));
        result.put("functional-extension-tests", Collections.singletonMap("include", Collections.emptyList()));
        result.put("extensions-jvm-tests", Collections.singletonMap("include", Collections.emptyList()));
        result.put("integration-tests-alternative-jdk", Collections.singletonMap("include", Collections.emptyList()));
        writeJsonResult(result);
    }

    private void writeJsonResult(Map<String, Object> result) throws IOException {
        outputFile.getParentFile().mkdirs();

        ObjectMapper mapper = new ObjectMapper();
        mapper.enable(SerializationFeature.INDENT_OUTPUT);

        mapper.writeValue(outputFile, result);
        getLog().info("Written result to: " + outputFile.getAbsolutePath());
        getLog().info("Result: " + mapper.writeValueAsString(result));
    }
}
