=== Infinispan Client Configuration

You can either configure the Infinispan client via the relevant Camel Infinispan component & endpoint options, or you
may use the https://quarkus.io/guides/infinispan-client#configuration-reference[Quarkus Infinispan extension configuration properties].

Note that if you choose to use Quarkus Infinispan configuration properties, you *must* add an injection point for the `RemoteCacheManager` in order for it to be discoverable by the Camel Infinispan component. For example:

[source,java]
----
public class Routes extends RouteBuilder {
    // Injects the default unnamed RemoteCacheManager
    @Inject
    RemoteCacheManager cacheManager;

    // If configured, injects an optional named RemoteCacheManager
    @Inject
    @InfinispanClientName("myNamedClient")
    RemoteCacheManager namedCacheManager;

    @Override
    public void configure() {
        // Route configuration here...
    }
}

----

=== Configuring Camel Infinispan for Quarkus Dev Services

To take advantage of https://quarkus.io/guides/infinispan-dev-services[Quarkus Dev Services for Infinispan], the Camel Infinispan component can be configured as follows in `application.properties`.

[source,properties]
----
# Dev / test mode configuration
quarkus.infinispan-client.devservices.port=31222

# These are the default credentials for Quarkus Infinispan Dev services
%dev,test.camel.component.infinispan.username=admin
%dev,test.camel.component.infinispan.password=password
%dev,test.camel.component.infinispan.secure=true
%dev,test.camel.component.infinispan.hosts=localhost:31222

# Prod mode configuration
%prod.camel.component.infinispan.username=prod-user
%prod.camel.component.infinispan.password=prod-password
%prod.camel.component.infinispan.secure=true
%prod.camel.component.infinispan.hosts=infinispan.prod:11222
----

Note that if you choose to use https://quarkus.io/guides/infinispan-client#configuration-reference[Quarkus Infinispan extension configuration properties] to configure the Infinispan client, then the above configuration is not necessary.

=== Camel Infinispan `InfinispanRemoteAggregationRepository` in native mode

If you chose to use the `InfinispanRemoteAggregationRepository` in native mode, then you must xref:extensions/core.adoc#quarkus.camel.native.reflection.serialization-enabled[enable native serialization support].
