#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: 'Report Build Status'
description: 'Reports the current build status to a given GitHub issue'
inputs:
  status:
    description: 'The current job status'
    required: true
    default: ${{ job.status }}
outputs:
  overall-build-status:
    description: 'The aggregated status of all workflow steps. Will be empty unless the status input property is set to verify'
    value: ${{ steps.report.outputs.overall_build_status }}

runs:
  using: "composite"
  steps:
    - name: Report build status
      id: report
      shell: bash
      run: |
        ./mvnw ${CQ_MAVEN_ARGS} verify -N -Pbuild-notification -Dstatus=${{ inputs.status }} -DissueId=${{ env.ISSUE_ID }} -Dtoken=${{ secrets.GITHUB_TOKEN }} -DbuildId=$(cat ~/build-data/build-id.txt) -Drepo=${GITHUB_REPOSITORY} -Dbranch=$(git branch --show-current) -Dbranch-commit=$(cat ~/build-data/main-sha.txt)
