#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: 'Setup Java'
description: 'Sets up Java on the runner node'
inputs:
  distribution:
    description: 'The JDK distribution'
    required: true
    default: 'temurin'
  java-version:
    description: 'The JDK version'
    required: true
    default: '17'

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}