#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Check Dependency Convergence

on:
  schedule:
    # Run every sunday at 12PM
    - cron: '0 12 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx3000m
  CQ_MAVEN_ARGS: -V -ntp -e -Daether.connector.http.connectionMaxTtl=120
  # TODO: Create a reporting issue
  ISSUE_ID: ???

jobs:
  check-dependency-convergence:
    if: github.repository == 'apache/camel-quarkus'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set Build Info
        run: |
          [ ! -d ~/build-data ] && mkdir -p ~/build-data
          echo "${{ github.run_id }}-${{ github.run_number }}-$(uuidgen)" > ~/build-data/build-id.txt
          git rev-parse HEAD > ~/build-data/main-sha.txt
      - name: Build Camel Quarkus
        run: ./mvnw ${CQ_MAVEN_ARGS} clean install -Dquickly -T1C
      - name: Install Groovy
        run:
          sudo apt install groovy --no-install-recommends -y
      - name: Create Superapp
        run: |
          groovy tooling/scripts/create-superapp.groovy
      - name: Run checks
        run: |
          # Copy maven wrapper
          cp -r .mvn ${{ runner.temp }}/camel-quarkus-superapp/
          cp ./mvnw ${{ runner.temp }}/camel-quarkus-superapp/
          
          # Run dependency convergence checks
          cd ${{ runner.temp }}/camel-quarkus-superapp/
          ./mvnw ${CQ_MAVEN_ARGS} clean verify
      - name: Report Build Failure
        if: failure() || cancelled()
        run: |
          ./mvnw ${CQ_MAVEN_ARGS} verify -N -Pbuild-notification -Dstatus=${{ job.status }} -DissueId=${{ env.ISSUE_ID }} -Dtoken=${{ secrets.GITHUB_TOKEN }} -DbuildId=$(cat ~/build-data/build-id.txt) -Drepo=${GITHUB_REPOSITORY} -Dbranch=$(git rev-parse --abbrev-ref HEAD) -Dbranch-commit=$(cat ~/build-data/main-sha.txt)
