#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Camel Quarkus CI

on:
  push:
    branches:
      - main
      - camel-main
      - quarkus-main
      - "[0-9]+.[0-9]+.x"
    paths-ignore:
      - '**.adoc'
      - 'Jenkinsfile'
      - 'Jenkinsfile.*'
      - 'KEYS'
      - 'LICENSE.txt'
      - 'NOTICE.txt'
      - 'camel-quarkus-sbom.*'
  pull_request:
    branches:
      - main
      - camel-main
      - quarkus-main
      - "[0-9]+.[0-9]+.x"
    paths-ignore:
      - '**.adoc'
      - 'Jenkinsfile'
      - 'Jenkinsfile.*'
      - 'KEYS'
      - 'LICENSE.txt'
      - 'NOTICE.txt'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx3000m
  CQ_MAVEN_ARGS: -V -ntp -Dhttp.keepAlive=false -e
  TESTCONTAINERS_RYUK_DISABLED: true

jobs:
  pre-build-checks:
    if: github.repository == 'jamesnetherton/camel-quarkus'
    runs-on: ubuntu-latest
    outputs:
      continue-build: ${{ steps.pre-build-checks.outputs.continue-build }}
      run-checks: ${{ steps.init.outputs.run-checks }}
    steps:
      - name: Initialize
        id: init
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            echo "run-checks=true" >> $GITHUB_OUTPUT
          else
            echo "run-checks=false" >> $GITHUB_OUTPUT
          fi
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        if: steps.init.outputs.run-checks == 'true'
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout
        uses: actions/checkout@v2
        if: steps.init.outputs.run-checks == 'true'
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Pre build checks
        id: pre-build-checks
        run: |
          if [[ "${{ steps.init.outputs.run-checks }}" == "true" ]]; then
            ./mvnw clean install -pl poms/bom -am -Dcq.flatten-bom.format --fail-never ${CQ_MAVEN_ARGS}
            ./mvnw clean install -f poms/bom ${CQ_MAVEN_ARGS}

            cd ../../

            if [[ -z "$(git status --porcelain)" ]]; then
              echo "continue-build=true" >> $GITHUB_OUTPUT
            else
              mkdir ./dependabot-pr
              echo ${{ github.head_ref }} > ./dependabot-pr/BRANCH_REF
              echo "$GITHUB_REF" | awk -F / '{print $3}' >  ./dependabot-pr/PR_NUMBER
              git diff -p --binary > ./dependabot-pr/changes.patch

              echo "continue-build=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "continue-build=true" >> $GITHUB_OUTPUT
          fi
      - name: Upload dependabot changeset
        uses: actions/upload-artifact@v2
        if: steps.pre-build-checks.outputs.continue-build == 'false'
        with:
          name: dependabot-pr-changeset
          path: dependabot-pr/
          retention-days: 1

  initial-mvn-install:
    if: needs.pre-build-checks.outputs.continue-build == 'true'
    runs-on: ubuntu-latest
    needs: pre-build-checks
    outputs:
      matrix: ${{ steps.set-native-matrix.outputs.matrix }}
    env:
      MAVEN_OPTS: -Xmx4400m
    steps:
      - name: Check free space on disk
        run: |
          df -h /
