name: 'Test Report'
on:
  workflow_run:
    workflows: ['Camel Quarkus CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: surefire-reports-*
        name: Camel Quarkus Test Report
        path: '*.xml'
        reporter: java-junit
